name: Release

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  # publish:
  #   name: Publish package to NPM
  #   runs-on: ubuntu-latest
  #   environment: release

  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         persist-credentials: false

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: npm
  #         registry-url: https://registry.npmjs.org

  #     - name: Publish to NPM
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #         NPM_CONFIG_PROVENANCE: true
  
  fetch-version-from-npm:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest package version
        id: get_version
        run: |
          VERSION=$(curl -s https://registry.npmjs.org/classnames/latest | jq -r '.version')
          echo "::set-output name=version::$VERSION"

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: fetch-version-from-npm
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        run: gh release create ${{ needs.fetch-version-from-npm.outputs.version}} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
