name: Release

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  publish:
    name: Publish package to NPM and Create GitHub Release
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Get package version
        run: |
          VERSION=$(npm pkg get version | xargs)
          echo "Package version is $VERSION"
          echo "::set-output name=version::$VERSION"

      # - name: Publish to NPM
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     NPM_CONFIG_PROVENANCE: true

      - name: Extract release notes from CHANGELOG.md
        id: changelog_reader
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          RELEASE_NOTES=$(awk -v ver="$VERSION" '/^## /{flag=0} $0~ver{flag=1} flag' CHANGELOG.md)
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          echo "::set-output name=release_notes::$RELEASE_NOTES"

      - name: Create GitHub Release
        run: gh release create ${{ steps.get_version.outputs.version }} --title ${{ steps.get_version.outputs.version }} --notes "${{ steps.changelog_reader.outputs.release_notes }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
